apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservices-app
data:
  AUTH_DB: "auth_service_db"
  USER_DB: "user_service_db"
  ORDER_DB: "order_service_db"
  JWT_ACCESS_TOKEN_EXPIRATION: "900000"
  JWT_REFRESH_TOKEN_EXPIRATION: "604800000"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  USER_SERVICE_URL: "http://user-service:8080"
  RANDOM_NUMBER_SERVICE_URL: "http://random-number-service:8080"