apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microservices-app
type: Opaque
stringData:
  AUTH_USER: "postgres"
  AUTH_PASSWORD: "2283"
  USER_USER: "postgres"
  USER_PASSWORD: "2283"
  ORDER_USER: "postgres"
  ORDER_PASSWORD: "2283"
  REDIS_PASSWORD: "redispass"
  JWT_SECRET: "super-secret-key-at-least-32-characters-long-for-hmac-sha256"